<?php
namespace App\GraphQL\Types;

use App\Grade;
use App\UniClass;
use Doctrine\DBAL\Types\BigIntType;
use Doctrine\DBAL\Types\DateTimeType;
use Doctrine\DBAL\Types\StringType;
use GraphQL\Type\Definition\Type;
use Illuminate\Support\Facades\Schema;
use Rebing\GraphQL\Support\Facades\GraphQL;
use Rebing\GraphQL\Support\Type as GraphQLType;

class UniClassType extends GenericType
{
    protected $attributes = [
        'name' => 'UniClass',
        'description' => 'A singular class',
        'model' => UniClass::class,
    ];
    public function fields(): array
    {
        $return = parent::fields(); // TODO: Change the autogenerated stub


        // adding additional fields
        $add = [
            'grades' => [
                'type' => Type::listOf(GraphQL::type('Grade')),
                'description' => 'The grades of this individual',

            ],
            'users' => [
                'type' => Type::listOf(GraphQL::type('User')),
                'description' => 'The students taking this class',

            ],
            'teacher' => [
                'type' => GraphQL::type('User'),
                'description' => 'The teacher of this class',

            ],
        ];

        $return = array_merge($return, $add);
        //$return= $add;

        //dd($return);

        return $return;
    }
}
