<?php

namespace App\GraphQL\Queries;

use App\GraphQL\Types\RoleType;
use Closure;
use App\User;
use Doctrine\DBAL\Types\BigIntType;
use Doctrine\DBAL\Types\DateTimeType;
use Doctrine\DBAL\Types\StringType;
use Illuminate\Support\Arr;
use Illuminate\Support\Facades\Schema;
use Rebing\GraphQL\Support\Facades\GraphQL;
use GraphQL\Type\Definition\ResolveInfo;
use GraphQL\Type\Definition\Type;
use Rebing\GraphQL\Support\Query;

class UsersQuery extends GenericQuery
{

    protected $attributes = [
        'name' => 'users',
        'type' => 'User',
        'class' => User::class,
    ];

    public function args(): array
    {
        $return = parent::args(); // TODO: Change the autogenerated stub

        return $return;
    }

    public function resolve($root, $args, $context, ResolveInfo $resolveInfo, Closure $getSelectFields)
    {
        $return = parent::resolve($root, $args, $context, $resolveInfo, $getSelectFields); // TODO: Change the autogenerated stub

        //$role =
        return $return;
    }

}
